services:
  mongodb:
    image: mongo:6
    container_name: interneers_lab_mongodb
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    # command: [mongod --auth ]
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
